group:
  - climabench
task: climate_text
dataset_path: eci-io/climate-evalutaion
dataset_name: null #climatext
dataset_kwargs: {data_files:{"train": ['ClimaText/train-data/Wiki-Doc-Train.tsv'], "validation": ['ClimaText/dev-data/Wikipedia (dev).tsv', 'ClimaText/dev-data/Wiki-Doc-Dev.tsv'], "test": ["ClimaText/test-data/10-Ks (2018, test).tsv", "ClimaText/test-data/Claims (test).tsv", "ClimaText/test-data/Wikipedia (test).tsv", "ClimaText/test-data/Wiki-Doc-Test.tsv"]}}
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
fewshot_split: validation
doc_to_text: "Given the following statement, is it relevant to climate change or not:\n{{sentence}}\nAnswer:"
doc_to_target: "{{label}}"
doc_to_choice: "{{['irrelevant', 'relevant']}}"
process_docs: !function utils.filter_binary
should_decontaminate: false
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: !function utils.f1
    aggregation: !function utils.agg_f1
    higher_is_better: true
