group:
  - climabench
task: climate_fever_boolean
dataset_path: climate_fever
output_type: multiple_choice
training_split: test
validation_split: test
test_split: test
doc_to_text: "Is the following statement on climate correct or misinformation:\n{{claim}}\nAnswer:"
doc_to_target: "{{claim_label}}"
doc_to_choice: "{{['correct', 'misinformation']}}"
process_docs: !function utils.filter_binary
should_decontaminate: false
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: !function utils.f1
    aggregation: !function utils.agg_f1
    higher_is_better: true
