group:
  - climabench
task: climate_eng
dataset_path: eci-io/climate-evalutaion
dataset_name: null #climate_eng
dataset_kwargs: {data_files:{"train": ['ClimateEng/train.csv'], "validation": ['ClimateEng/val.csv'], "test": ["ClimateEng/test.csv"]}}
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
fewshot_split: validation
doc_to_target: "{{label}}"
doc_to_text: "Given the five categories: 'general', 'politics', 'ocean/water', 'agriculture/forestry', 'disaster', assign the following statement to one of the categories: '{{text}}'. \nAnswer:"
# "Assign the following statement to one of the five given categories: '{{text}}'. \nAnswer:"
doc_to_choice: "{{['general', 'politics', 'ocean/water', 'agriculture/forestry', 'disaster']}}"
process_docs: !function utils.filter_multi
should_decontaminate: false
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: !function utils.f1
    aggregation: !function utils.agg_f1
    higher_is_better: true
