group:
  - climabench
task: cdp_qa_combined
dataset_path: eci-io/climate-evalutaion
dataset_name: cdp_qa
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
fewshot_split: validation
doc_to_target: "{{label}}"
doc_to_text: "Given a question and an answer, examine if the answer addresses the question.\nQuestion: {{question}}\nAnswer: {{answer}}\n\nOutput:"
doc_to_choice: "{{['no', 'yes']}}"
process_docs: !function utils.filter_main
should_decontaminate: false
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
  - metric: !function utils.f1
    aggregation: !function utils.agg_f1
    higher_is_better: true
