task: exams_science_ar
dataset_path: eci-io/climate-evalutaion
dataset_name: exams
output_type: multiple_choice
# training_split: train
# validation_split: validation
test_split: test
doc_to_text: question_stem
doc_to_target: "{{answer}}" #"{{choices.label.index(answerKey.lstrip())}}"
doc_to_choice: "{{choices.text}}"
should_decontaminate: true
process_docs: !function utils.process_docs_filter_science
# doc_to_decontamination_query: question_stem
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
